#!/usr/bin/env python
# -*- coding: cp1252-*-
import csv
import datetime
import logging

from helpers import get_csv_line

SECONDS_PER_DAY = 86400 # = 24 * 60 * 60


def import_trips_in_visum(v, path_trips_file, path_out_trips_for_visum, factor=1.0):
    """
    Reads the trips generated by MATSim to a text-file which can be read by the Visum-Fahrgastmodul
    :param path_trips_file: path to the MATSim-trip-file
    :param path_visum_version: path to the Visum-version
    :param path_out_trips_for_visum: path to the text-file in which the trips are written for importing in Visum by the Fahrgastmodul
    :return: 
    """
    logging.info("pfad trips-file: {}".format(path_trips_file))
    logging.info("pfad trips-file-for-visum-out: {}".format(path_out_trips_for_visum))

    v.apl.go_offline(mit_fzps=True, params={})

    fzps = v.apl.hole_fahrzeitprofile()
    fzp_pro_id = {}
    for fzp in fzps:
        id = int(fzp.nummer())
        fzp_pro_id[id] = fzp
    logging.info("fzp verarbeitet. anz fzp: {}".format(len(fzp_pro_id)))
    hps = v.netz.hole_haltepunkte()
    hsnr_pro_hpnr = {}
    for hp in hps:
        hpnr = int(hp.nummer())
        hsnr = int(hp.com_objekt.AttValue("STOPAREA\STOP\NO"))
        hsnr_pro_hpnr[hpnr] = hsnr
    logging.info("hp und hs verarbeitet. anz hps: {}".format(len(hsnr_pro_hpnr)))

    logging.info("start trips für visum schreiben")
    header = """
$VISION
* VisumInst
* 10.11.06
*
*
* Tabelle: Versionsblock
$VERSION:VERSNR;FILETYPE;LANGUAGE;UNIT
4.00;Att;DEU;KM
*
*
* Tabelle: ÖV-Teilwege\n
"""
    spaltennamen_list = ["$OEVTEILWEG:VONHSTNR",
                         "NACHHSTNR",
                         "DATENSATZNR",
                         "WEGIND",
                         "TWEGIND",
                         "PFAHRT",
                         "LinName",
                         "LinRouteName",
                         "RichtungCode",
                         "FZProfilName",
                         "EingabeHstAbfahrtstag",
                         "EingabeHstAbfahrtszeit",
                         "EingabeHStNr"]
    with open(path_trips_file) as trips_file, open(path_out_trips_for_visum, "w") as trips_for_visum:
        trips_for_visum.write(header)
        trips_for_visum.write(get_csv_line(spaltennamen_list))
        reader = csv.DictReader(trips_file, delimiter="\t")
        journey_id_old = None
        weg_index = 0
        for row in reader:
            journey_id = int(row["journey_id"])
            if journey_id != journey_id_old:
                weg_index += 1
                index = 1
            if row["mode"] == "pt":
                hpnr_von = int(row["boarding_stop"].split("_")[0])
                hsnr_von = hsnr_pro_hpnr[hpnr_von]
                hpnr_bis = int(row["alighting_stop"].split("_")[0])
                fzpid = int(row["route"].split("_")[0])
                fzp = fzp_pro_id[fzpid]
                time_sec = int(row["departure_time"]) % SECONDS_PER_DAY # < SECONDES_PER_DAY wird von Visum beim Einlesen gefordert!
                l = [hsnr_von,
                     hsnr_pro_hpnr[hpnr_bis],
                     journey_id,
                     weg_index,
                     index,
                     factor,
                     fzp.com_objekt.AttValue("LineName").encode("cp1252"),
                     fzp.com_objekt.AttValue("LineRouteName").encode("cp1252"),
                     fzp.com_objekt.AttValue("DIRECTIONCODE").encode("cp1252"),
                     fzp.com_objekt.AttValue("Name").encode("cp1252"),
                     1,
                     str(datetime.timedelta(seconds=time_sec)),
                     hsnr_von]
                trips_for_visum.write(get_csv_line(l))
                index += 1
            journey_id_old = journey_id

    logging.info("trips gelesen und geschrieben")

    # TODO einlesen in visum


if __name__ == "__main__":
    import python_path
    python_path.load()
    import vipy.visum
    path_trips_file = r"\\V00925\80_MatSim\30_TopDown\visum\00_Fahrgastmodul\matsim_trips.txt"
    path_visum_version = r"\\V00925\80_MatSim\30_TopDown\visum\REF_STEP2030_M_mPM_mCeva_UML_DWV_01_UeL_BAV_v05_intMatrix.ver"
    path_out_trips_for_visum = r"\\V00925\80_MatSim\30_TopDown\visum\00_Fahrgastmodul\matsim_trips_for_visum.txt"

    v = vipy.visum.Visum()
    v.lade_version(path_visum_version)
    logging.info("visum-version geöffnet")

    import_trips_in_visum(v, path_trips_file, path_out_trips_for_visum)